import { AppThemeProvider } from "@/providers/appThemeProvider";
import { NextAuthProvider } from "@/providers/nextAuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppThemeProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </AppThemeProvider>
      </body>
    </html>
  );
}
